#!/bin/bash
# Start zone1 (Linux) using dynamic memory allocation.
# Usage: bash start_zone1.sh
# zone1_ram.json is generated by hvisor-virtio daemon after HVISOR_ZONE_M_ALLOC.

set -e

SCRIPT_DIR=$(dirname "$(realpath "$0")")
EXAMPLES_DIR="$SCRIPT_DIR/.."

ZONE_CONFIG="$EXAMPLES_DIR/zone1_linux.json"
RAM_JSON="$EXAMPLES_DIR/zone1_ram.json"  # generated by virtio daemon

if [ ! -f "$ZONE_CONFIG" ]; then
    echo "Error: zone config not found: $ZONE_CONFIG"
    exit 1
fi

if [ ! -f "$RAM_JSON" ]; then
    echo "Error: zone1_ram.json not found: $RAM_JSON"
    echo "Make sure hvisor-virtio daemon has run and allocated memory first."
    exit 1
fi

echo "Starting zone1..."
echo "  config : $ZONE_CONFIG"
echo "  ram    : $RAM_JSON"

# hvisor resolves kernel_filepath relative to cwd.
# zone1_linux.json uses "../Guest/vmlinux.bin", so we must run from
# the examples directory where that relative path resolves correctly.
cd "$EXAMPLES_DIR"
hvisor zone start_dyna "$ZONE_CONFIG" "$RAM_JSON"
